# Etapa 01: Define imagem base do Node
FROM node:20-alpine

# Etapa 02: Define o diretório de trabalho do container 
WORKDIR /app

# Etapa 03: Copiar arquivos de dependência e instalar 
COPY package*.json ./
RUN npm install 

# Etapa 04: Copiar o restante dos arquivos e gerar Prisma
COPY . .
RUN npx prisma generate
RUN npm run build

# Etapa 05: Expor a porta da aplicação 
EXPOSE 3000

# Etapa 06: Comando padrão
CMD "npm"